### PR TITLE
amogus.png

### PR DESCRIPTION
**Pull request by Anuken**

### CODE REVIEW

**Comment by Erisfiregamer1** [comment]
sus 😳

**Comment by littelcat456** [comment]
> sus 😳

When the imposter is sus 😳

**Comment by Ilikepieitsgood** [comment]
what is this

**Comment by littelcat456** [comment]
> what is this

Sus

**Comment by Ilikepieitsgood** [comment]
Yes

**Comment by Kappandrew** [comment]
When the crawler is sussy! 😳

**Pull request merged**
